### ISSUE TITLE
JOSS review: Changelog, README and Vignettes

### ISSUE THREAD

**Issue by maximelenormand** [TommyJones/tidylda#73]
I managed to install both the CRAN and GitHub versions. In both cases, I ran the examples without any problems.

- The differences between the current CRAN version and the development version are not clear. It would be nice to add a changelog somewhere to list all the changes made between the different (futur) CRAN versions and between the current CRAN version and the development GitHub version. It seems that there is no mention of either the CRAN or development GitHub version nor the way to install the package in the paper.

- The dependencies are listed in the DESCRIPTION file but not in the README.

- The package contains three vignettes that are not presented on the GitHub repository.

This is not mandatory, of course, but a nice way to address these issues could be to build a website for your package using pkgdown (https://pkgdown.r-lib.org/). A tidyverse template is available at https://github.com/tidyverse/tidytemplate.

[#6800](https://github.com/openjournals/joss-reviews/issues/6800)

**Comment by TommyJones** [comment]
Hi. Thanks again for the review.

* I have a [NEWS.md file](https://github.com/TommyJones/tidylda/blob/main/NEWS.md) that contains updates between versions. I add to the list as I make changes so the current state reflects changes to the development version. Does that meet the need you flagged?
* I'd rather not have dependencies listed in two places. I'm afraid that it would introduce the possibility of human error. (i.e., I will forget to update the README.) If acceptance of the package into JOSS hinges on this, I'll add dependencies to README,  but I'd prefer not to. `tidytext`, for example, [does not list its dependencies in the README](https://github.com/juliasilge/tidytext).
* The vignettes are [here](https://github.com/TommyJones/tidylda/tree/main/vignettes). They're in R markdown format as CRAN does the PDF rendering on their end.

Do the above work for you?

**Comment by maximelenormand** [comment]
Hi, regarding the changelog and dependencies, it would be beneficial to add a few sentences to the README to inform users that all changes are listed in the NEWS.md file and that the dependencies can be found in the DESCRIPTION.md file.

Please, add a paragraph describing the different vignettes and the way to compile them.

Do not forget to mention the CRAN and development GitHub versions in the paper and the way to install them.

**Comment by TommyJones** [comment]
Ok. I'll get these taken care of shortly.

- [ ] Reference NEWS.md in README
- [ ] Reference DESCRIPTION in README
- [ ] Add paragraph to README describing vignettes and how to compile them
- [ ] Add paragraph to the JOSS paper describing vignettes
- [ ] Mention CRAN and development versions and how to install them in the JOSS paper

**Comment by TommyJones** [comment]
All of the above are taken care of as of this commit: c4eb725b095f3fd58be6bd3657c9825cc72a98b1
