### ISSUE TITLE
JOSS review: Comments on the paper

### ISSUE THREAD

**Issue by maximelenormand** [TommyJones/tidylda#76]
I have two general comments on the paper.

- The summary should focus on your package and not on the tidy universe. Please use this section to describe the functionality and purpose of your package for a diverse, non-specialist audience.

- The state of need/field section could be developed by listing the main packages that implement topic models in R (and other languages) and explaining in detail why your software is much better than the other options.

[#6800](https://github.com/openjournals/joss-reviews/issues/6800)

**Comment by TommyJones** [comment]
I believe I addressed these issues with this commit 6e8e2f53a43d360fa0324e445b09e43bbd6ef8a8

Can you confirm that's sufficient (or not)? I'll leave this issue open until then.

**Comment by maximelenormand** [comment]
That's fine by me. Thanks.

**Comment by TommyJones** [comment]
Awesome. Thank you so much for your time and effort in reviewing and making both the paper and the tidylda package better.
